-- Create the 'tools' table
CREATE TABLE tools (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    purpose text NOT NULL,
    description text NOT NULL,
    "howToUse" text NOT NULL,
    region text NOT NULL,
    "businessUnit" text NOT NULL,
    "languageSupport" text NOT NULL,
    cost text NOT NULL CHECK (cost IN ('Free', 'Paid')),
    access text NOT NULL CHECK (access IN ('Open', 'Controlled')),
    views integer NOT NULL DEFAULT 0,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

-- RLS (Row Level Security) Policies
-- 1. Enable RLS for the tools table
ALTER TABLE tools ENABLE ROW LEVEL SECURITY;

-- 2. Allow public read access to everyone
CREATE POLICY "Allow public read access" ON tools
    FOR SELECT
    USING (true);

-- 3. Allow authenticated users to insert, update, and delete their own tools
-- Note: This assumes you have a way to link tools to users, which is not in the current schema.
-- You would need to add a user_id column to the tools table and modify the policies accordingly.
-- For now, allowing all authenticated users to perform these actions.
CREATE POLICY "Allow insert for authenticated users" ON tools
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow update for authenticated users" ON tools
    FOR UPDATE
    USING (auth.role() = 'authenticated')
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow delete for authenticated users" ON tools
    FOR DELETE
    USING (auth.role() = 'authenticated');

-- Seed Data (Optional)
-- You can use this to insert the initial mock data into your Supabase table.
INSERT INTO tools (name, purpose, description, "howToUse", region, "businessUnit", "languageSupport", cost, access, views, "createdAt", "updatedAt")
VALUES
('SynthWeaver', 'Automated content generation for marketing campaigns.', 'SynthWeaver uses advanced generative models to create compelling marketing copy, social media posts, and email newsletters. It helps marketing teams scale their content production.', '1. Connect your brand guidelines.\n2. Select a content template (e.g., blog post, tweet).\n3. Provide a brief prompt or keywords.\n4. Generate and refine the output.', 'Global', 'Marketing', 'English, Spanish, French', 'Paid', 'Controlled', 1258, '2023-01-15T09:30:00Z', '2023-10-26T14:00:00Z'),
('DataScribe', 'Transcribes audio and video files with high accuracy.', 'DataScribe is an AI-powered transcription service that supports over 50 languages and dialects. It features speaker identification and custom vocabulary.', '1. Upload your audio or video file.\n2. Select the language.\n3. Start the transcription process.\n4. Review and export the transcript in various formats (TXT, SRT, VTT).', 'North America', 'Operations', '50+ Languages', 'Paid', 'Controlled', 890, '2023-02-20T11:00:00Z', '2023-11-05T18:20:00Z'),
('InsightSphere', 'Analyzes customer feedback to identify trends and sentiment.', 'InsightSphere connects to various data sources like surveys, reviews, and support tickets. It uses natural language processing to extract actionable insights and visualize data.', '1. Connect your data sources (e.g., Zendesk, SurveyMonkey).\n2. Configure analysis dashboards.\n3. Monitor real-time sentiment and key topics.\n4. Generate reports to share with stakeholders.', 'EMEA', 'Customer Experience', 'English, German', 'Paid', 'Controlled', 2340, '2023-03-10T16:45:00Z', '2023-11-12T11:30:00Z'),
('CodePilot', 'AI assistant for writing and debugging code.', 'CodePilot integrates with popular IDEs to provide code completions, suggest refactoring, and help identify bugs. It supports a wide range of programming languages.', '1. Install the CodePilot extension for your IDE (e.g., VS Code).\n2. Sign in with your account.\n3. Start typing, and CodePilot will provide suggestions.\n4. Use chat to ask coding questions or debug errors.', 'Global', 'Engineering', 'Python, JavaScript, Java, C++', 'Free', 'Open', 5432, '2023-04-01T10:00:00Z', '2023-11-15T09:00:00Z'),
('HR-Bot', 'Automates responses to common HR questions.', 'An internal chatbot that integrates with the company''s knowledge base to answer employee questions about policies, benefits, and procedures, freeing up the HR team.', '1. Access the chatbot via Slack or the company portal.\n2. Ask your question in plain language (e.g., "how much vacation time do I have?").\n3. If the bot cannot answer, it will escalate to an HR representative.', 'Global', 'Human Resources', 'English', 'Free', 'Controlled', 765, '2023-05-25T14:20:00Z', '2023-10-30T12:00:00Z'),
('SecureScan', 'Identifies security vulnerabilities in applications.', 'SecureScan uses AI to perform static and dynamic analysis of codebases, identifying potential security threats and compliance issues before they reach production.', '1. Integrate SecureScan into your CI/CD pipeline.\n2. Configure scanning rules for your projects.\n3. Review scan results in the dashboard.\n4. Triage and fix identified vulnerabilities.', 'Global', 'Engineering', 'Multiple', 'Paid', 'Controlled', 987, '2023-06-18T08:00:00Z', '2023-11-10T17:45:00Z');
